name: Build hugo

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
    types: [closed]

  workflow_dispatch:

  workflow_call:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.merged == true  }}
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.91.2"
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Setup Pages
        if: github.ref == 'refs/heads/master'
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        if: github.ref == 'refs/heads/master'
        with:
          # Upload entire repository
          path: "./public"

      - name: Deploy
        uses: actions/deploy-pages@v1
        if: github.ref == 'refs/heads/master'

      # - name: Install AWS CLI
      #   uses: unfor19/install-aws-cli-action@v1.0.3
      #   with:
      #     version: 2 # default
      #     verbose: false # default
      #     arch: amd64 # allowed values: amd64, arm64
      #     rootdir: "" # defaults to "PWD"
      #     workdir: "" # defaults to "PWD/unfor19-awscli"

      # - name: Deploy static site to S3 bucket
      #   run: aws s3 sync ./public/ s3://site-et-digest --delete --endpoint-url http://ib.bizmrg.com
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: ru-msk
